### ISSUE TITLE
Improve config file syntax

### ISSUE THREAD

**Issue by atraides** [atraides/pumpmeup#7]
The current configuration file format contains redundancies. To avoid said redundancies and make it easier to match the MQTT naming convention the file should be redesigned.

Here is an example how it should look like.

```yaml
location:
  hvac:
    sensors:
      basement:
        study:
          sensor-1:
            name: Test Sensor
            pin: D4
            provide: 
              - temperature
            model: DHT22
    controllers:
      basement:
        controller-1:
          name: Basement circulation pump
          pin: D23
          type: pump
          subtype: relay
          provide:
            - status
          consume:
            - manage
          interval: 120
      ground:
        controller-2:
          name: Ground floor circulation pump
          pin: D24
          type: pump
          subtype: relay
          provide:
            - status
          consume:
            - manage
          interval: 120
```
